// Content layer for standalone top-level pages reconstructed from the clean WP DB
// (generated by the toolkit's scripts/extract-toplevel.mjs). Same SEAM note as
// services.ts: swap the JSON import for a DRF fetch when the CMS is live.

import type { Metadata } from "next";
import raw from "@/lib/data/top-level-pages.json";

export type TopLevelPage = {
  id: number;
  slug: string;
  path: string;
  title: string;
  excerpt: string;
  seoTitle: string;
  metaDescription: string;
  focusKeyword: string;
  html: string;
};

const pages = raw as TopLevelPage[];

export function getPage(slug: string): TopLevelPage | undefined {
  return pages.find((p) => p.slug === slug);
}

/** Build Next Metadata from a top-level page's migrated SEO fields. */
export function pageMetadata(slug: string, type: "article" | "website" = "article"): Metadata {
  const p = getPage(slug);
  if (!p) return {};
  return {
    title: p.seoTitle || p.title,
    description: p.metaDescription || p.excerpt,
    keywords: p.focusKeyword ? [p.focusKeyword] : undefined,
    alternates: { canonical: p.path },
    openGraph: { title: `${p.title} | Inocul8`, description: p.metaDescription, url: p.path, type },
  };
}
