// Content layer for the /what-we-do service tree.
//
// Today this reads the static, typed content extracted from the (clean) legacy
// WordPress DB — see src/lib/data/what-we-do.json (generated by the toolkit's
// scripts/clean-content.mjs). It is the single source of truth for the service
// routes and the sitemap.
//
// SEAM: when the Django/DRF CMS is live, swap the JSON import for a fetch in the
// accessors below (getCategories/getCategory/getService). The exported types and
// function shapes are the contract the routes depend on — keep them stable.

import type { IconName } from "@/components/ui/icon";
import raw from "@/lib/data/what-we-do.json";

export type ServicePage = {
  id: number;
  path: string;
  slug: string;
  parentPath: string;
  title: string;
  excerpt: string;
  seoTitle: string;
  metaDescription: string;
  focusKeyword: string;
  html: string;
};

export type ServiceCategory = {
  slug: string;
  path: string;
  label: string;
  icon: IconName;
  blurb: string;
  page: ServicePage;
  services: ServicePage[];
};

const pages = raw as ServicePage[];
const WWD = "/what-we-do";

// Per-category presentation metadata + display order. Keyed by the real slug
// (preserves SEO equity — do not rename these slugs).
const CATEGORY_META: Record<string, { label: string; icon: IconName; blurb: string; order: number }> = {
  "immunization-services": {
    label: "Immunization Services",
    icon: "baby",
    blurb: "The complete childhood immunization ladder, birth to 4–6 years, following the Nigerian NPI schedule.",
    order: 1,
  },
  "sexual-reproductive-health-services": {
    label: "Sexual & Reproductive Health",
    icon: "heart-pulse",
    blurb: "Confidential HPV, hepatitis, HIV PrEP/PEP and related vaccines and care for adults.",
    order: 2,
  },
  "travel-health-services": {
    label: "Travel Health Services",
    icon: "plane",
    blurb: "Destination-based travel vaccine bundles and documented records accepted by embassies.",
    order: 3,
  },
  "myhealth-services": {
    label: "myHealth Services",
    icon: "stethoscope",
    blurb: "Ongoing, affordable support plans for living well with chronic infections like hepatitis B and herpes.",
    order: 4,
  },
  "other-immunization-services": {
    label: "Other Immunization",
    icon: "syringe",
    blurb: "Flu, shingles, rabies, typhoid, cholera, pneumococcal, tetanus and more — for every adult need.",
    order: 5,
  },
  "employee-wellness-initiative": {
    label: "Employee Wellness",
    icon: "briefcase",
    blurb: "On-site corporate immunization, health talks and screenings for a healthier, happier workforce.",
    order: 6,
  },
};

const byPath = new Map(pages.map((p) => [p.path, p]));

export const hubPage = byPath.get(WWD);

export function getCategories(): ServiceCategory[] {
  return pages
    .filter((p) => p.parentPath === WWD)
    .map((page) => {
      const meta = CATEGORY_META[page.slug];
      return {
        slug: page.slug,
        path: page.path,
        label: meta?.label ?? page.title,
        icon: meta?.icon ?? "syringe",
        blurb: meta?.blurb ?? page.excerpt,
        page,
        services: pages
          .filter((s) => s.parentPath === page.path)
          .sort((a, b) => a.title.localeCompare(b.title, "en")),
      };
    })
    .sort((a, b) => (CATEGORY_META[a.slug]?.order ?? 99) - (CATEGORY_META[b.slug]?.order ?? 99));
}

export function getCategory(slug: string): ServiceCategory | undefined {
  return getCategories().find((c) => c.slug === slug);
}

export function getService(categorySlug: string, serviceSlug: string): ServicePage | undefined {
  const cat = getCategory(categorySlug);
  return cat?.services.find((s) => s.slug === serviceSlug);
}

/** Static params for /what-we-do/[category]. */
export function getCategoryParams(): { category: string }[] {
  return getCategories().map((c) => ({ category: c.slug }));
}

/** Static params for /what-we-do/[category]/[service]. */
export function getServiceParams(): { category: string; service: string }[] {
  return getCategories().flatMap((c) => c.services.map((s) => ({ category: c.slug, service: s.slug })));
}

/** Every URL in the /what-we-do tree — for the sitemap. */
export function allServicePaths(): string[] {
  return [WWD, ...pages.filter((p) => p.parentPath.startsWith(WWD)).map((p) => p.path)];
}
